### PR TITLE
Add setCast as per...

### PR DESCRIPTION
**Pull request by da3dsoul**
https://github.com/xbmc/xbmc/commit/84478ea69f3fdd5556fa5e5a0bbe5ccaf6ba06b1

### CODE REVIEW

**Comment by da3dsoul** [comment]
Will do.

**Comment by da3dsoul** [comment]
Alright. Looks okay. Let me know if anything else needs done, and I will add it.

**Comment by da3dsoul** [comment]
Okay, I think I'm done for awhile.

**Comment by romanvm** [comment]
Thanks!

**Pull request merged**
